name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: ls -R
    # Download the repo
    - name: Checkout repo
      uses: actions/checkout@master
    - run: ls -R

    # Crete zip file
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release1.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - run: ls -R

    # Upload as an artifact of the current workflow
    - name: Upload build zip artifact
      uses: actions/upload-artifact@v2
      with:
        path: release1.zip
    - run: ls -R

        
