name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'

    # Upload as an artifact of the current workflow
    - name: Upload build zip artifact
      uses: actions/upload-artifact@v1
      with:
        name: release.zip
        path: release.zip
        
